#!/usr/bin/env bash

base_dir=$(pwd)

imageVersion=`grep -e "version '" build.gradle \
    | awk -F '\047' '{print $2}' \
    | awk 'sub(/-(SNAPSHOT|snapshot)/, "")'`
imageName=lavenderx/springboot-angular-seed
containerName=springboot-angular-seed

# Get container status
running=$(docker inspect --format="{{ .State.Running }}" ${containerName} 2> /dev/null)

if [ $? -eq 1 ];  then
    echo "The specific container doesn't exist!"
else
    # Check container running status
    if [ "${running}" = "true" ];  then
        docker stop ${containerName}
    fi

    docker rm ${containerName}
fi

imageId=$(docker images -q ${imageName}:${imageVersion} 2> /dev/null)
if [ ! -z ${imageId} ];  then
    docker rmi ${imageId}
fi

./gradlew clean buildImage

docker run --name ${containerName} --net host -d -e HEAP_SIZE=1g -e PROFILE=dev ${imageName}:${imageVersion}