#!/bin/bash

base_dir=$(pwd)

APPLICATION_VERSION=1.0
IMAGE_NAME=lavenderx/springboot-angular-seed:${APPLICATION_VERSION}
CONTAINER_NAME=springboot-angular-seed

# Container status
running=$(docker inspect --format="{{ .State.Running }}" ${CONTAINER_NAME} 2> /dev/null)

if [ $? -eq 1 ];  then
    echo "The specific container does't exist!"
else
    # Check container running status
    if [ "${running}" = "true" ];  then
        docker stop ${CONTAINER_NAME}
    fi

    docker rm ${CONTAINER_NAME}
fi

if [ ! -z ${IMAGE_NAME} ];  then
    docker rmi ${IMAGE_NAME}
fi

gradle clean buildImage

docker run --name ${CONTAINER_NAME} --net host -d -e HEAP_SIZE=1g -e PROFILE=dev ${IMAGE_NAME}